# Zsh configuration module

db_module_zsh_register() {
    db_register_module "zsh" \
        "db_module_zsh_plan" \
        "db_module_zsh_apply"
}

db_module_zsh_plan() {
    local enable=$(db_yaml_get '.zsh.enable' 'true')
    if [[ "$enable" != "true" ]]; then
        return 0
    fi
    
    local include_file=$(db_yaml_get '.zsh.include_file' "$HOME/.zshrc.devboost")
    local zshrc="${HOME}/.zshrc"
    
    if [[ ! -f "$include_file" ]]; then
        db_log_info "Would create: $include_file"
    fi
    
    if [[ ! -f "$zshrc" ]] || ! grep -q "# >>> devboost include start" "$zshrc" 2>/dev/null; then
        db_log_info "Would inject devboost include block into: $zshrc"
    fi
}

db_render_zsh_devboost() {
    local znap_path=$(db_yaml_get '.zsh.znap_path' "$HOME/.zsh-snap")
    local enable_starship=$(db_yaml_get '.prompt.enable_starship' 'true')
    local starship_config=$(db_yaml_get '.prompt.starship_config' "$HOME/.config/starship.toml")
    local use_atuin=$(db_yaml_get '.zsh.history.use_atuin' 'true')
    local fzf_enable=$(db_yaml_get '.zsh.fzf.enable' 'true')
    local fzf_files=$(db_yaml_get '.zsh.fzf.default_command_files' 'fd --type f --hidden --follow --exclude .git')
    local fzf_dirs=$(db_yaml_get '.zsh.fzf.default_command_dirs' 'fd --type d --hidden --follow --exclude .git')
    local enable_mise=$(db_yaml_get '.toolchains.enable_mise' 'true')
    local enable_direnv=$(db_yaml_get '.direnv.enable' 'true')
    local clicolor=$(db_yaml_get '.aesthetics.clicolor' 'true')
    local lsc_colours=$(db_yaml_get '.aesthetics.lsc_colours' 'ExFxCxDxBxegedabagacad')
    local aliases_enable=$(db_yaml_get '.zsh.aliases.enable' 'true')
    
    cat << EOF
# Generated by devboost - DO NOT EDIT MANUALLY
export EDITOR="nvim"
export LANG="en_US.UTF-8"

setopt HIST_IGNORE_ALL_DUPS HIST_REDUCE_BLANKS SHARE_HISTORY INC_APPEND_HISTORY
autoload -Uz compinit && compinit -u
setopt AUTO_CD NO_BEEP

# znap
source "${znap_path}/znap.zsh"

# prompt
EOF
    
    if [[ "$enable_starship" == "true" ]]; then
        echo "export STARSHIP_CONFIG=\"${starship_config}\""
        echo 'eval "$(starship init zsh)"'
    fi
    
    cat << 'EOF'

# plugins
znap source zsh-users/zsh-autosuggestions
znap source zsh-users/zsh-syntax-highlighting

# nav/search/history
eval "$(zoxide init zsh)"
EOF
    
    if [[ "$use_atuin" == "true" ]]; then
        echo 'eval "$(atuin init zsh)"'
    fi
    
    if [[ "$fzf_enable" == "true" ]]; then
        echo 'eval "$(fzf --zsh 2>/dev/null || /opt/homebrew/bin/fzf --zsh 2>/dev/null || true)"'
        echo "export FZF_DEFAULT_COMMAND='${fzf_files}'"
        echo 'export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"'
        echo "export FZF_ALT_C_COMMAND='${fzf_dirs}'"
    fi
    
    cat << EOF

# toolchains & per-project env
EOF
    
    if [[ "$enable_mise" == "true" ]]; then
        echo 'eval "$(mise activate zsh)"'
    fi
    
    if [[ "$enable_direnv" == "true" ]]; then
        echo 'eval "$(direnv hook zsh)"'
    fi
    
    cat << EOF

# aesthetics
EOF
    
    if [[ "$clicolor" == "true" ]]; then
        echo 'export CLICOLOR=1'
    fi
    
    echo "export LSCOLORS=\"${lsc_colours}\""
    
    cat << EOF

# aliases
EOF
    
    if [[ "$aliases_enable" == "true" ]]; then
        cat << EOF
alias ls='eza -alg --git --group --time-style=relative'
alias cat='bat -pp'
alias grep='rg'
alias find='fd'
alias du='dust'
alias df='duf'
alias ps='procs'
alias lg='lazygit'
alias tm='tmux attach -t main || tmux new -s main'
alias please='sudo $(fc -ln -1)'
EOF
    fi
}

db_module_zsh_apply() {
    local enable=$(db_yaml_get '.zsh.enable' 'true')
    if [[ "$enable" != "true" ]]; then
        return 0
    fi
    
    local include_file=$(db_yaml_get '.zsh.include_file' "$HOME/.zshrc.devboost")
    local zshrc="${HOME}/.zshrc"
    
    # Generate and write .zshrc.devboost
    local content=$(db_render_zsh_devboost)
    db_write_file "$include_file" "$content"
    
    # Inject include block into .zshrc
    local include_block="# >>> devboost include start
[ -f \"\$HOME/.zshrc.devboost\" ] && source \"\$HOME/.zshrc.devboost\"
# <<< devboost include end
"
    
    if [[ ! -f "$zshrc" ]]; then
        if [[ "${DB_DRY_RUN:-false}" == "true" ]]; then
            db_log_info "Would create: $zshrc"
        else
            echo "$include_block" > "$zshrc"
            db_log_success "Created: $zshrc"
        fi
    elif ! grep -q "# >>> devboost include start" "$zshrc" 2>/dev/null; then
        if [[ "${DB_DRY_RUN:-false}" == "true" ]]; then
            db_log_info "Would append include block to: $zshrc"
        else
            db_backup_file "$zshrc"
            echo "" >> "$zshrc"
            echo "$include_block" >> "$zshrc"
            db_log_success "Injected include block into: $zshrc"
        fi
    else
        db_log_verbose "Include block already present in: $zshrc"
    fi
}

