package modules

import (
	"fmt"
	"strings"

	"github.com/rolfsormo/devboost/config"
)

// renderAtuinConfig ports db_render_atuin_config.
func renderAtuinConfig(cfg *config.Config) string {
	filterMode := cfg.Get("zsh.history.atuin.filter_mode", "directory")
	return "# Generated by devboost - DO NOT EDIT MANUALLY\n" +
		"# Atuin filter mode: controls how command history is shared between shells\n" +
		"# Options: global, host, session, directory, workspace\n" +
		"# Default: directory (context-specific history for developers)\n" +
		fmt.Sprintf("filter_mode = %q\n", filterMode)
}

// renderZshDevboost ports db_render_zsh_devboost: builds the entire
// .zshrc.devboost content as a sequence of config-gated sections, in the
// same order as the bash version's cat/echo composition.
func renderZshDevboost(cfg *config.Config) string {
	znapPath := cfg.Get("zsh.znap_path", "~/.zsh-snap")
	enableStarship := cfg.Get("prompt.enable_starship", "true") == "true"
	starshipConfig := cfg.Get("prompt.starship_config", "~/.config/starship.toml")
	useAtuin := cfg.Get("zsh.history.use_atuin", "true") == "true"
	fzfEnable := cfg.Get("zsh.fzf.enable", "true") == "true"
	fzfFiles := cfg.Get("zsh.fzf.default_command_files", "fd --type f --hidden --follow --exclude .git")
	fzfDirs := cfg.Get("zsh.fzf.default_command_dirs", "fd --type d --hidden --follow --exclude .git")
	enableMise := cfg.Get("toolchains.enable_mise", "true") == "true"
	enableDirenv := cfg.Get("direnv.enable", "true") == "true"
	clicolor := cfg.Get("aesthetics.clicolor", "true") == "true"
	lscColours := cfg.Get("aesthetics.lsc_colours", "ExFxCxDxBxegedabagacad")
	aliasesEnable := cfg.Get("zsh.aliases.enable", "true") == "true"

	var b strings.Builder

	b.WriteString("# Generated by devboost - DO NOT EDIT MANUALLY\n")
	b.WriteString("export EDITOR=\"nvim\"\n")
	b.WriteString("export LANG=\"en_US.UTF-8\"\n\n")
	b.WriteString("setopt HIST_IGNORE_ALL_DUPS HIST_REDUCE_BLANKS SHARE_HISTORY INC_APPEND_HISTORY\n")
	b.WriteString("setopt AUTO_CD NO_BEEP\n\n")
	b.WriteString("# znap owns completion init: it redefines compinit/compdef as no-ops and\n")
	b.WriteString("# runs its own deferred, precmd-hook-based compinit after loading (see\n")
	b.WriteString("# ~/.zsh-snap/scripts/init.zsh). Calling compinit here ourselves, before\n")
	b.WriteString("# znap is sourced, would run a second full completion pass into a\n")
	b.WriteString("# different dumpfile — pure redundant cost with no effect (znap's\n")
	b.WriteString("# no-op override discards any completions we'd have registered anyway).\n")
	b.WriteString("# znap\n")
	fmt.Fprintf(&b, "source %q\n\n", znapPath+"/znap.zsh")

	b.WriteString("# prompt\n")
	if enableStarship {
		fmt.Fprintf(&b, "export STARSHIP_CONFIG=%q\n", starshipConfig)
		b.WriteString(`eval "$(starship init zsh)"` + "\n")
	}

	b.WriteString("\n# plugins\n")
	b.WriteString("znap source zsh-users/zsh-autosuggestions\n")
	b.WriteString("znap source zsh-users/zsh-syntax-highlighting\n\n")
	b.WriteString("# nav/search/history\n")
	b.WriteString(`eval "$(zoxide init zsh)"` + "\n")

	if useAtuin {
		b.WriteString(`eval "$(atuin init zsh)"` + "\n")
	}
	if fzfEnable {
		b.WriteString(`eval "$(fzf --zsh 2>/dev/null || /opt/homebrew/bin/fzf --zsh 2>/dev/null || true)"` + "\n")
		fmt.Fprintf(&b, "export FZF_DEFAULT_COMMAND=%q\n", fzfFiles)
		b.WriteString(`export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"` + "\n")
		fmt.Fprintf(&b, "export FZF_ALT_C_COMMAND=%q\n", fzfDirs)
	}

	b.WriteString("\n# toolchains & per-project env\n")
	if enableMise {
		b.WriteString(`eval "$(mise activate zsh)"` + "\n")
	}
	if enableDirenv {
		b.WriteString(`eval "$(direnv hook zsh)"` + "\n")
	}

	b.WriteString("\n# aesthetics\n")
	if clicolor {
		b.WriteString("export CLICOLOR=1\n")
	}
	fmt.Fprintf(&b, "export LSCOLORS=%q\n", lscColours)

	b.WriteString("\n# aliases\n")
	if aliasesEnable {
		b.WriteString(`alias ls='eza -alg --git --group --time-style=relative'` + "\n")
		b.WriteString(`alias cat='bat -pp'` + "\n")
		b.WriteString(`alias grep='rg'` + "\n")
		b.WriteString(`alias find='fd'` + "\n")
		b.WriteString(`alias du='dust'` + "\n")
		b.WriteString(`alias df='duf'` + "\n")
		b.WriteString(`alias ps='procs'` + "\n")
		b.WriteString(`alias lg='lazygit'` + "\n")
		b.WriteString(`alias tm='tmux attach -t main || tmux new -s main'` + "\n")
		b.WriteString(`alias please='sudo $(fc -ln -1)'` + "\n")
	}

	return b.String()
}
